### ISSUE TITLE
Color modes support for generate stylesheet plugin

### ISSUE THREAD

**Issue by deckchairlabs** [deckchairlabs/theme-ui.macro#7]
Generate stylesheet plugin should support generating rules based on color modes.

It could detect color modes defined in the colors tokens, and if they match `dark` `light` add a `prefers-color-scheme` media selector. 

This wouldn't work for custom color modes though, it might be more useful to have a new configuration option `colorSchemePrefix` which will generate something like the following.

```css
.theme-ui-color-scheme-happy .button-base {
  background-color: yellow;
}
```

Or if custom properties are used.

```css
:root {
  --colors-primary: red;
}

.theme-ui-color-scheme-happy {
  --colors-primary: yellow;
}

.button-primary {
  background-color: var(--colors-primary);
}
```
